version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 25
  - package-ecosystem: cargo
    directory: '/src-tauri'
    schedule:
      interval: daily
    open-pull-requests-limit: 25
